/**
 * Authentication error codes
 * Used for consistent error handling across the application
 */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'AUTH_001',
  TOKEN_EXPIRED = 'AUTH_002',
  TOKEN_INVALID = 'AUTH_003',
  USER_NOT_FOUND = 'AUTH_004',
  EMAIL_NOT_VERIFIED = 'AUTH_005',
  ACCOUNT_DEACTIVATED = 'AUTH_006',
  PASSWORD_RESET_TOKEN_INVALID = 'AUTH_007',
  PASSWORD_RESET_TOKEN_EXPIRED = 'AUTH_008',
  PASSWORD_CHANGE_REQUIRED = 'AUTH_009',
  NEW_PASSWORD_SAME_AS_CURRENT = 'AUTH_010',
  RATE_LIMIT_EXCEEDED = 'AUTH_011',
  TOKEN_BLACKLISTED = 'AUTH_012',
  PASSWORDS_DO_NOT_MATCH = 'AUTH_013',
  WEAK_PASSWORD = 'AUTH_014',
}
